//! Markdown export for meeting summaries.
//!
//! Section content stored by the summary pipeline is already
//! GFM-flavored markdown (bullets, pipe tables, checkbox lists,
//! `**bold**` inline emphasis), so unlike `pdf.rs` / `docx.rs` this
//! renderer is close to a structural passthrough: it wraps the
//! `MeetingExportData` (see [`crate::export::commands`]) in a title,
//! a metadata block, and one `##` heading per section, without
//! reinterpreting the content itself.

use super::pdf::{format_date_human, MeetingExportData};

/// Render the supplied meeting data as a Markdown document.
///
/// Unlike PDF/DOCX export this cannot fail — there is no external
/// renderer to report errors from.
pub fn export_meeting_to_markdown(data: &MeetingExportData) -> String {
    let title = if data.meeting_title.is_empty() {
        "Untitled meeting"
    } else {
        &data.meeting_title
    };

    let mut out = format!("# {title}\n\n");
    out.push_str(&format!(
        "_Generated by Personal Meetly • Template: {}_\n\n",
        data.template_name
    ));

    out.push_str(&format!("- **Meeting ID:** {}\n", data.meeting_id));
    out.push_str(&format!(
        "- **Date:** {}\n",
        format_date_human(&data.created_at)
    ));
    if let Some(duration) = data.duration.as_deref().filter(|d| !d.is_empty()) {
        out.push_str(&format!("- **Duration:** {duration}\n"));
    }
    if let Some(attendees) = data
        .attendees
        .as_deref()
        .map(str::trim)
        .filter(|a| !a.is_empty())
    {
        out.push_str(&format!("- **Attendees:** {attendees}\n"));
    }
    out.push('\n');

    for section in &data.sections {
        out.push_str(&format!("## {}\n\n", section.title));
        let content = section.content.trim();
        if content.is_empty() {
            out.push_str("_(no content)_\n\n");
        } else {
            out.push_str(content);
            out.push_str("\n\n");
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::export::pdf::SectionContent;

    fn sample_data(sections: Vec<SectionContent>) -> MeetingExportData {
        MeetingExportData {
            meeting_id: "m-1".into(),
            meeting_title: "Weekly Planning".into(),
            created_at: "2026-06-29T14:00:00Z".into(),
            duration: Some("00:42:13".into()),
            attendees: Some("Ana, Bruno".into()),
            template_name: "Standard".into(),
            sections,
        }
    }

    #[test]
    fn renders_title_metadata_and_sections_verbatim() {
        let data = sample_data(vec![SectionContent {
            title: "Action Items".into(),
            format: "list".into(),
            content: "- [ ] Ship export [[Ana]] Due: 2026-07-01".into(),
            item_format: None,
        }]);

        let md = export_meeting_to_markdown(&data);

        assert!(md.starts_with("# Weekly Planning\n\n"));
        assert!(md.contains("Template: Standard"));
        assert!(md.contains("**Meeting ID:** m-1"));
        assert!(md.contains("**Duration:** 00:42:13"));
        assert!(md.contains("**Attendees:** Ana, Bruno"));
        assert!(md.contains("## Action Items\n\n"));
        assert!(md.contains("- [ ] Ship export [[Ana]] Due: 2026-07-01"));
    }

    #[test]
    fn empty_meeting_title_falls_back_to_placeholder() {
        let mut data = sample_data(vec![]);
        data.meeting_title = String::new();
        let md = export_meeting_to_markdown(&data);
        assert!(md.starts_with("# Untitled meeting\n\n"));
    }

    #[test]
    fn empty_section_content_renders_placeholder() {
        let data = sample_data(vec![SectionContent {
            title: "Summary".into(),
            format: "paragraph".into(),
            content: "   ".into(),
            item_format: None,
        }]);
        let md = export_meeting_to_markdown(&data);
        assert!(md.contains("## Summary\n\n_(no content)_\n\n"));
    }

    #[test]
    fn attendees_and_duration_are_omitted_when_absent() {
        let mut data = sample_data(vec![]);
        data.duration = None;
        data.attendees = None;
        let md = export_meeting_to_markdown(&data);
        assert!(!md.contains("**Duration:**"));
        assert!(!md.contains("**Attendees:**"));
    }
}
