export const en: Record<string, string> = {
    "chat.error.message": "Error: {message}",
    "chat.header.title": "Chat with Meetings",
    "chat.header.configureModel": "No model configured · Configure →",
    "chat.header.configureModelAria": "Open Settings to change chat model",
    "chat.provider.local": "Local",
    "chat.provider.cloud": "Cloud",
    "chat.provider.custom": "Custom",
    "chat.provider.localTooltip": "Runs on this device. Queries stay local.",
    "chat.provider.cloudTooltip": "Queries are sent to a cloud provider.",
    "chat.provider.customTooltip": "Queries go to your custom OpenAI-compatible endpoint.",
    "chat.scope.aria": "Search scope",
    "chat.scope.thisMeeting": "This meeting",
    "chat.scope.meetingNamed": "Meeting: {title}",
    "chat.scope.allMeetings": "All meetings",
    "chat.scope.folder": "This folder",
    "chat.scope.folderNamed": "Folder: {name}",
    "chat.scope.searchResults": "Search results",
    "chat.scope.liveRecording": "Live recording",
    "chat.orphan.disclosure":
        "This meeting was deleted. Its chat thread is no longer available, and earlier answers may still quote deleted content.",
    "chat.load.failed": "Chat could not be loaded. Check your model configuration and try again.",
    "chat.mode.label": "Retrieval depth",
    "chat.mode.fast": "Fast",
    "chat.mode.deep": "Deep",
    "chat.mode.fastDescription": "One retrieval pass for a quicker answer.",
    "chat.mode.deepDescription":
        "May take longer and make additional requests to your configured Chat provider.",
    "chat.mode.liveDescription": "Live Chat reads the current transcript directly.",
    "chat.live.disclosure":
        "This will send your in-progress transcript content to a non-local provider. Continue?",
    "chat.live.launcher": "Ask about this recording",
    "chat.clear.confirm": "Clear this chat? This cannot be undone.",
    "chat.clear.aria": "Clear chat",
    "chat.closeAria": "Close chat",
    "chat.empty.description": "Ask questions about your meetings.",
    "chat.empty.searchDescription": "The AI will search your transcripts, summaries, and notes.",
    "chat.suggested.aria": "Suggested prompts",
    "chat.suggested.askAria": "Ask: {prompt}",
    "chat.suggested.actionItems": "What were the action items?",
    "chat.suggested.keyDecisions": "Summarize the key decisions",
    "chat.suggested.attendees": "Who attended and what did they discuss?",
    "chat.suggested.openQuestions": "What were the open questions?",
    "chat.suggested.todayActionItems": "List the action items from today's meetings",
    "chat.suggested.todaySummary": "Summarize today's meetings",
    "chat.suggested.globalActionItems": "What action items are open across my meetings?",
    "chat.suggested.recentMeetings": "Summarize my most recent meetings",
    "chat.suggested.weeklyDecisions": "What decisions were made this week?",
    "chat.suggested.commonTopics": "What topics came up most often?",
    "chat.searching": "Searching meetings...",
    "chat.input.placeholder": "Ask about your meetings...",
    "chat.sendAria": "Send message",
    "chat.stop.aria": "Stop generating",
    "chat.message.copy": "Copy answer",
    "chat.message.copied": "Copied!",
    "chat.message.sources": "Sources:",
    "chat.message.openMeetingAria": "Open meeting {title}",
    "chat.message.liveSourceAria": "Live recording transcript source",
    "chat.preparation.initialRetrievalStarted": "Searching your meetings for relevant evidence...",
    "chat.preparation.initialRetrieval": "Initial retrieval complete: {completed} of {total}.",
    "chat.preparation.plannerRound":
        "Reviewing meetings for more evidence: round {completed} of {total}.",
    "chat.preparation.additionalSearch": "Additional search: {completed} of {total}.",
    "chat.preparation.answerGeneration": "Preparing answer: {completed} of {total}.",
    "notes.header.title": "Notes",
    "notes.header.loadError": "Couldn't load notes",
    "notes.status.saving": "Saving...",
    "notes.status.unsaved": "Unsaved",
    "notes.status.saved": "Saved",
    "notes.status.savedAt": "Saved {time}",
    "notes.action.save": "Save",
    "notes.action.saveAria": "Save notes",
    "notes.action.delete": "Delete notes",
    "notes.action.hide": "Hide notes",
    "notes.retry": "Retry",
    "notes.delete.confirm": "Delete these notes? This cannot be undone.",
    "notes.toast.saveFailed": "Failed to save notes",
    "notes.toast.loadFailed": "Failed to load notes",
    "notes.toast.deleted": "Notes deleted",
    "notes.toast.deleteFailed": "Failed to delete notes",
    "app.recording.showNotesAria": "Show recording notes",
    "app.recording.notesFlushFailed":
        "Couldn't save notes before stopping. Try again or stop without saving.",
    "app.meetingDetails.showNotesAria": "Show notes",
    "app.meetingDetails.showChatAria": "Show chat",
    "app.meetingDetails.showChatTitle": "Chat with this meeting (Ctrl/Cmd+Shift+M)",
    "app.home.showChatAria": "Chat with all meetings",
    "app.sidebar.askFolder": "Ask this folder",
    "app.sidebar.askSearchResults": "Ask about these results",
    "app.sidebar.searchInputAria": "Search meeting content",
    "app.sidebar.searchPlaceholder": "Search meeting content...",
    "app.sidebar.clearSearchAria": "Clear search",
    "app.sidebar.searchForcedLexical": "Exact keyword search",
    "app.sidebar.searchLexicalFallback": "Semantic search unavailable; using keywords",
    "app.sidebar.searchUnavailable": "Search unavailable",
    "app.sidebar.noResults": "No results.",
    "app.sidebar.filterFolderAria": "Filter by folder {name}",
    "app.sidebar.clearFolderFilterAria": "Clear folder filter",
    "app.sidebar.clearFolderFilter": "clear",
    "app.sidebar.provenance.hybrid": "Hybrid",
    "app.sidebar.provenance.meaning": "Meaning",
    "app.sidebar.provenance.keyword": "Keyword",
    "app.sidebar.provenance.title": "Title",
    "app.sidebar.provenance.transcript": "Transcript",
    "app.sidebar.provenance.summary": "Summary",
    "app.sidebar.provenance.notes": "Notes",
};
